// =============================================================================
// Aeternum — Health Connect launch-mode + manifest fix config plugin
// =============================================================================
// WHY THIS EXISTS
// react-native-health-connect launches its permission UI through
// `registerForActivityResult` (see HealthConnectPermissionDelegate). Expo's
// default MainActivity is declared with `android:launchMode="singleTask"`.
//
// `singleTask` and `ActivityResultLauncher` conflict: when the Health Connect
// permission screen returns, `singleTask` can re-route the task through
// onNewIntent / tear down the Activity instance that registered the result
// contract, so the result is never delivered to the launcher. On many devices
// this surfaces as an INSTANT CRASH the moment the permission dialog is
// launched — the exact "crash on the permissions screen" symptom.
//
// The fix is `singleTop`, which keeps deep-link / single-instance behavior
// intact for expo-router while leaving the activity-result plumbing alive.
//
// We ALSO de-duplicate the `ACTION_SHOW_PERMISSIONS_RATIONALE` intent-filter,
// which the Health Connect plugin can add twice.
//
// Because `android/` is gitignored and regenerated by `expo prebuild` on every
// EAS build, this MUST be a config plugin — a hand-edit to AndroidManifest.xml
// would be wiped on the next clean build. Idempotent.
// =============================================================================

const { withAndroidManifest } = require('@expo/config-plugins')

const RATIONALE_ACTION = 'androidx.health.ACTION_SHOW_PERMISSIONS_RATIONALE'

function getMainActivity(manifest) {
  const app = manifest['manifest']?.['application']?.[0]
  if (!app || !Array.isArray(app['activity'])) return null
  return (
    app['activity'].find(
      (a) => a['$']?.['android:name'] === '.MainActivity',
    ) ?? null
  )
}

// Replace singleTask with singleTop so ActivityResultLauncher callbacks survive.
function fixLaunchMode(activity) {
  if (activity['$']?.['android:launchMode'] === 'singleTask') {
    activity['$']['android:launchMode'] = 'singleTop'
  }
}

// Collapse duplicate ACTION_SHOW_PERMISSIONS_RATIONALE intent-filters into one.
function dedupeRationaleFilter(activity) {
  if (!Array.isArray(activity['intent-filter'])) return
  let seen = false
  activity['intent-filter'] = activity['intent-filter'].filter((f) => {
    const actions = f['action'] ?? []
    const isRationale = actions.some(
      (a) => a['$']?.['android:name'] === RATIONALE_ACTION,
    )
    if (!isRationale) return true
    if (seen) return false // drop the duplicate
    seen = true
    return true
  })
}

module.exports = function withHealthConnectLaunchMode(config) {
  return withAndroidManifest(config, (cfg) => {
    const activity = getMainActivity(cfg.modResults)
    if (!activity) {
      throw new Error(
        '[withHealthConnectLaunchMode] Could not find .MainActivity in ' +
          'AndroidManifest.xml — the Health Connect permission crash fix was ' +
          'NOT applied. Update this plugin.',
      )
    }
    fixLaunchMode(activity)
    dedupeRationaleFilter(activity)
    return cfg
  })
}
