// =============================================================================
// Aeternum — Health Connect permission-delegate config plugin
// =============================================================================
// WHY THIS EXISTS
// react-native-health-connect v3 requires the host Activity to register an
// ActivityResultLauncher for the Health Connect permission contract by calling
//
//     HealthConnectPermissionDelegate.setPermissionDelegate(this)
//
// inside MainActivity.onCreate (after super.onCreate). The library's own
// `app.plugin.js` ONLY patches AndroidManifest.xml — it does NOT touch
// MainActivity. Because `android/` is gitignored and regenerated by
// `expo prebuild` on every EAS build, any hand-edit to MainActivity.kt is wiped,
// the delegate is never registered, and the first time the user taps "Connect"
// the native `lateinit var requestPermission` is accessed uninitialized →
// UninitializedPropertyAccessException → app crash, no permission dialog.
//
// This plugin re-injects the registration into MainActivity.onCreate at prebuild
// time so it survives every clean build. Idempotent: it no-ops if the import or
// the call is already present.
// =============================================================================

const { withMainActivity } = require('@expo/config-plugins')

const IMPORT_LINE =
  'import dev.matinzd.healthconnect.permissions.HealthConnectPermissionDelegate'

// Registration must run AFTER super.onCreate(...) but inside onCreate so the
// ActivityResultLauncher is registered while the Activity is still CREATED
// (registering after RESUMED throws).
const REGISTER_LINE =
  '    HealthConnectPermissionDelegate.setPermissionDelegate(this)'

function addImport(contents) {
  if (contents.includes(IMPORT_LINE)) return contents
  // Insert the import right after the package declaration so it's always valid.
  return contents.replace(
    /^(package .+)$/m,
    `$1\n\n${IMPORT_LINE}`,
  )
}

function addRegistration(contents) {
  if (contents.includes('HealthConnectPermissionDelegate.setPermissionDelegate')) {
    return contents
  }

  // Match the first `super.onCreate(...)` call inside onCreate and append the
  // registration on the following line, preserving indentation style.
  const superCall = /(\n[ \t]*super\.onCreate\([^)]*\)\s*\n)/
  if (!superCall.test(contents)) {
    throw new Error(
      '[withHealthConnectPermissionDelegate] Could not find super.onCreate() in ' +
        'MainActivity — the Health Connect permission delegate was NOT injected. ' +
        'The permission dialog will crash. Update this plugin.',
    )
  }
  return contents.replace(superCall, `$1${REGISTER_LINE}\n`)
}

module.exports = function withHealthConnectPermissionDelegate(config) {
  return withMainActivity(config, (cfg) => {
    if (cfg.modResults.language !== 'kt') {
      throw new Error(
        '[withHealthConnectPermissionDelegate] Expected a Kotlin MainActivity ' +
          `but found "${cfg.modResults.language}". This plugin only supports Kotlin.`,
      )
    }
    let contents = cfg.modResults.contents
    contents = addImport(contents)
    contents = addRegistration(contents)
    cfg.modResults.contents = contents
    return cfg
  })
}
